Forms Milestone
AyoubMs/rails-blog pull request #7
Opened 2022-07-14 22:17 UTC by AyoubMs

In this commit, I: 
- added the current_user method to the ApplicationController, so that it returns the first user from the database.
- created forms for Post and Comment Creation with "form_with".
- I also added a form for likes.

2022-07-14 23:01 UTC, codepantha requested changes
# STATUS: REQUESTED CHANGES ♻️ 

## Hi @AyoubMs 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Meaningful commit message
✔️ Linter checks

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-14 23:01 UTC, codepantha commented on app/controllers/comments_controller.rb
> +      text: comment_params,
- [x] Please add a `new` action. to the `CommentsController`. This is a project requirement 🙏

2022-07-14 23:01 UTC, codepantha commented on config/routes.rb
> +    resources :likes, only: [:create]
- [x] Please add a route that goes to comments#new action which I suggested you add ☝️ in order to display the form to add a new comment 🙏

2022-07-14 23:01 UTC, codepantha commented on app/controllers/posts_controller.rb
> +    new_post.update_posts_counter
- [x] An error occurs while creating a new post for the logged-in user. This error occurs because of an undefined method `likes_counter`. Please fix this 🙏 
![image](https://user-images.githubusercontent.com/46839548/179104686-46f5bf35-906b-47b0-8b7e-ff71af2180ea.png)

2022-07-15 09:04 UTC, GzimAsani requested changes
### Hello @AyoubMs     :wave:   
 Good job so far, you've implemented almost all the requirements asked previously! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good work with your controllers :+1: 
 
 ## Required Changes 

- [x] _Check the comments below :arrow_double_down:_



 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-15 09:04 UTC, GzimAsani commented on app/controllers/posts_controller.rb
> +    new_post.likes_count = 0
- [x] Unfortunately, I am still getting the same error when trying to add a post as a logged-in user. Kindly fix this
![image](https://user-images.githubusercontent.com/62705947/179191549-dd040b04-856f-4b7a-8efa-e84ad6ee9fbc.png)

2022-07-15 09:35 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a 

### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-15 10:47 UTC, merged